# Generated by Django 2.1.7 on 2019-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_parijan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPNRoutingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('next_hop', models.IntegerField()),
            ],
        ),
    ]
